### ISSUE TITLE
2Captcha和yes Captcha

### ISSUE THREAD

**Issue by f-o-o-l** [Zakkoree/woiden_extend#1]
2Captcha3美元起充，能适配yes Captcha白嫖吗？

**Comment by Zakkoree** [comment]
前几天API方法都写好了,接入很容易,但需要加参数,本来参数就不少了,然后就嫌麻烦没有加,2Captcha也可以嫖点钱,就是浪费点时间识码,等有时间再加yes Captcha吧,应为我已经把写好的方法删了找不到了 🤦‍♂️
