### ISSUE TITLE
在Action服务器上套Warp*可能*可以大幅度提高续期概率

### ISSUE THREAD

**Issue by kkstone** [Zakkoree/woiden_extend#7]
今天发现使用Action服务器续期hax总过不去最后一步算术题页面的hcaptcha验证，无限报robot。套了cf warp之后一次成功，前后不超过五分钟，且语音验证码的概率大幅度提高。

- name: Connect to Cloudflare Warp
   uses: daycat/cloudflare-warp-actions@main
添加在安装依赖后，执行main.py之前。

**Comment by Zakkoree** [comment]
上个月挺稳定，就这两天存在了失败的情况，这个是v3的人机验证没搞明白，我测了几次，现在还是可以续订成功，不过你这样更换减速云的ip确实也是解决的一种方式，有时间试试

**Comment by Zakkoree** [comment]
彻底解决还得是v3，可惜没搞明白
